packages:
  - "shared/*"
  - "apps/*"
  - "backend"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "bcrypt"
  - "prisma"
  - "sharp"
  - "@nestjs/core"
  - "msw"
  - "puppeteer"
  - "unrs-resolver"
