import type { Metadata } from "next"
import { Noto_Sans } from "next/font/google"
import "./globals.css"
import { ViewTransition } from "react"
import { ThemeProvider } from "next-themes"
import { NuqsAdapter } from "nuqs/adapters/next"

const notoSans = Noto_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-noto-sans",
})

const fontFamily = `system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, var(--${notoSans.variable}), sans-serif`

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased bg-secondary dark:bg-background`}
        style={{
          fontFamily,
        }}
      >
        <NuqsAdapter>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </NuqsAdapter>
      </body>
    </html>
  )
}
